# Generated by Django 5.2.4 on 2025-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Torneio')),
                ('game', models.CharField(max_length=100, verbose_name='Jogo')),
                ('prize', models.CharField(max_length=100, verbose_name='Prêmio')),
                ('date_text', models.CharField(max_length=100, verbose_name='Data')),
                ('format_text', models.CharField(max_length=100, verbose_name='Formato')),
                ('image', models.ImageField(upload_to='tournaments/', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para a URL, gerado automaticamente.', unique=True)),
            ],
        ),
    ]
