# Generated by Django 5.2.3 on 2025-07-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
