# Generated by Django 5.2.3 on 2025-07-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_tournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('discussion', 'Discussão'), ('media', 'Imagem ou Vídeo')], default='discussion', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('valorant', 'Valorant'), ('csgo', 'CS:GO / CS2'), ('lol', 'League of Legends'), ('eldenring', 'Elden Ring'), ('hardware', 'Hardware'), ('geral', 'Dúvidas Gerais'), ('outro', 'Outro')], max_length=50)),
                ('conteudo', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/posts/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
