# Generated by Django 5.2.3 on 2025-08-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_like_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('jogo', models.CharField(max_length=100)),
                ('premio', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('formato', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='torneios/')),
                ('link_inscricao', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
