# Generated by Django 5.2.3 on 2025-08-11 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_torneio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
